### ISSUE TITLE
Backticks support?

### ISSUE THREAD

**Issue by SchumacherFM** [jackc/sqlfmt#6]
Thank you for this nice formatter! A pleasure to have it.

One minor suggestion: Currently this MySQL query fails to parse:
```sql
SELECT `tax_class`.* FROM `tax_class` WHERE (`tax_class`.`class_id`='3');
```
```
$ pbpaste | sqlfmt -u
2017/06/11 20:52:48 parse error: syntax error at character 73
Parse failed
```

Removing the backticks and it works.

Do you plan to support the backticks? 8-)

**Comment by jackc** [comment]
At the moment the parser is based on PostgreSQL syntax and PostgreSQL doesn't support backticks. I don't have any objection to supporting MySQL specific syntax as well, but I suspect it may be rather difficult.

**Comment by SchumacherFM** [comment]
I'll close it as too long inactive.
