### ISSUE TITLE
Parsing fails for unquoted identifiers

### ISSUE THREAD

**Issue by mxmCherry** [jackc/sqlfmt#9]
Did `go get -u github.com/jackc/sqlfmt/cmd/sqlfmt` a few minutes ago and trying to run it:

```bash
$ echo 'SELECT * FROM table' | sqlfmt
2017/11/15 01:03:53 parse error: syntax error at character 20
Parse failed
```

That's, umm, a bit surprising, as I'm quite used to write PG queries without quoting tables.

When you quote the table name - it works fine:

```bash
$ echo 'select * from "table"' | sqlfmt 
select
  *
from
  "table"
```

---

Seen this comment: https://github.com/jackc/sqlfmt/issues/7#issuecomment-326985548 so not actually expecting a fix (if it should be "fixed" at all?), just logging an issue.

Also, a bit of offtop question - it seems to support only SELECT statements, right? (as seen in `sql.y` file)

**Comment by jackc** [comment]
Yes, it only supports selects. And I think what is happening with "table" is it is considered a key word. Trying it with a different table name works.

```
$ echo 'SELECT * FROM foo' | sqlfmt
select
  *
from
  foo
```

**Comment by mxmCherry** [comment]
Oh, right, did not think about that - makes sense, thank you.
